{% set name = "uhi" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/uhi-{{ version }}.tar.gz
  sha256: 97fdf50ac0fefd954b74697a19b04e2ca8b9303a825f5294d31338316ce5ab52

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - poetry >=1.0.10
    - poetry-core
    - python >=3.6

  run:
    - numpy >=1.13.3
    - python >=3.6
    # Actually only required for [py<38] but require for all Python versions so this can be noarch: python
    - typing_extensions >=3.7

test:
  source_files:
    - tests
  imports:
    - uhi
    - uhi.typing
  commands:
    - pip check
    - pytest .
  requires:
    - pip
    - pytest
    - importlib_metadata
    - boost-histogram

about:
  home: https://github.com/Scikit-HEP/uhi
  summary: 'Unified Histogram Interface: tools to help library authors work with histograms'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
