{% set name = "uhi" %}
{% set version = "0.5.0" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uhi-{{ version }}.tar.gz
  sha256: 9559bbf2f38f18a2fc1d8f73139396068f88f898d6a9afc833207ec0fd59a31c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs

  run:
    - python >={{ python_min }}
    - numpy >=1.13.3
    - python-fastjsonschema
    # TODO: Drop after python_min is 3.9
    # c.f. https://github.com/scikit-hep/uhi/blob/3284e73c531c918306ee03dacbb19fb42d8fdf2b/pyproject.toml#L48
    - importlib-resources

test:
  source_files:
    - tests
  imports:
    - uhi
    - uhi.typing
  commands:
    - pip check
    - pytest .
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - importlib_metadata
    - boost-histogram

about:
  home: https://github.com/Scikit-HEP/uhi
  summary: 'Unified Histogram Interface: tools to help library authors work with histograms'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
