schema_version: 1

context:
  name: uhi
  version: "1.1.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/uhi-${{ version }}.tar.gz
  sha256: 98a39f0f3c01144b9769abbc95c31499667e6808b7c653af3dae0e846d0356b5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - numpy >=1.13.3
    - python-fastjsonschema
    # TODO: Drop after python_min is 3.11
    - typing_extensions

tests:
  - python:
      imports:
        - uhi
        - uhi.typing
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests
    requirements:
      run:
        - python ${{ python_min }}.*
        - pip
        - pytest
        - boost-histogram
        - dependency-groups
        - hist
        - h5py
    script:
      - pytest .

about:
  summary: "Unified Histogram Interface: tools to help library authors work with histograms"
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/Scikit-HEP/uhi

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
